econet:
    boudrate: 115200
    serial_file: /dev/ttyUSB3
    remove_lead_zero: 0
mqtt:
    ClientId: EcoMax920p1
    ServerIp: 192.168.1.111
    serverPort: 1883
    username: mqttuser
    password: mqttuser
    keepAliveTopic: ecomax_920_master
    keepAliveMsg: Online
    Substring: ecomax_set # not used
    Pubstring: ecomax_get # not used 

econet_set:
    pub_huw_temp: EcoNet/set_huw_temp
    pub_huw_pump_mode: EcoNet/set_huw_pump_mode
    pub_huw_temp_hysteresis: EcoNet/set_huw_temp_hysteresis
    pub_huw_container_disinfection: EcoNet/set_huw_container_disinfection
    pub_boiler_temp: EcoNet/set_boiler_temp
    pub_boiler_on_off: EcoNet/set_boiler_on_off
    pub_boiler_max_power_kw: EcoNet/set_boiler_max_power_kw
    pub_boiler_mid_power_kw: EcoNet/set_boiler_mid_power_kw
    pub_boiler_min_power_kw: EcoNet/set_boiler_min_power_kw
    pub_boiler_max_power_fan: EcoNet/set_boiler_max_power_fan
    pub_boiler_mid_power_fan: EcoNet/set_boiler_mid_power_fan
    pub_boiler_min_power_fan: EcoNet/set_boiler_min_power_fan
    pub_mixer_temp: EcoNet/set_mixer_temp
    pub_room_thermostat_summer_winter_mode: EcoNet/set_room_thermostat_summer_winter_mode
    pub_room_thermostat_night_temp: EcoNet/set_room_thermostat_night_temp
    pub_room_thermostat_day_temp: EcoNet/set_room_thermostat_day_temp
    pub_room_thermostat_operating_mode: EcoNet/set_room_thermostat_operating_mode
    pub_room_thermostat_hysteresis: EcoNet/set_room_thermostat_hysteresis
econet_get:
    sub_get_operating_status: EcoNet/get_operating_status
    sub_get_huw_temp: EcoNet/get_huw_temp
    sub_get_feeder_temp: EcoNet/get_feeder_temp
    sub_get_boiler_temp: EcoNet/get_boiler_temp
    sub_get_weather_temp: EcoNet/get_weather_temp
    sub_get_exhaust_temp: EcoNet/get_exhaust_temp
    sub_get_mixer_temp: EcoNet/get_mixer_temp
    sub_get_boiler_return_temp: EcoNet/get_boiler_return_temp
    sub_get_upper_buffer_temp: EcoNet/get_upper_buffer_temp
    sub_get_lower_buffer_temp: EcoNet/get_lower_buffer_temp
    sub_get_flame_sensor: EcoNet/get_flame_sensor
    sub_get_ecoster_home_temp: EcoNet/get_ecoster_home_temp
    sub_get_ecoster_home_temp_target: EcoNet/get_ecoster_home_temp_target
    sub_get_huw_temp_target: EcoNet/get_huw_temp_target
    sub_get_boiler_temp_target: EcoNet/get_boiler_temp_target
    sub_get_mixer_temp_target: EcoNet/get_mixer_temp_target
    sub_get_fuel_level: EcoNet/get_fuel_level
    sub_get_fan_out_power: EcoNet/get_fan_out_power
    sub_get_fan_in_power: EcoNet/get_fan_in_power
    sub_get_huw_pomp_state: EcoNet/get_huw_pomp_state
    sub_get_boiler_pomp_state: EcoNet/get_boiler_pomp_state
    sub_get_fuel_stream: EcoNet/get_fuel_stream
    sub_get_boiler_power_kw: EcoNet/get_boiler_power_kw
    sub_get_power_max_time: EcoNet/get_power_max_time
    sub_get_power_medium_time: EcoNet/get_power_medium_time
    sub_get_power_min_time: EcoNet/get_power_min_time
    sub_get_feeder_time: EcoNet/get_feeder_time
    sub_get_ignitions: EcoNet/get_ignitions
    sub_get_ignitions_fails: EcoNet/get_ignitions_fails
    sub_get_huw_pump_mode: EcoNet/get_huw_pump_mode
    sub_get_huw_temp_hysteresis: EcoNet/get_huw_temp_hysteresis
    sub_get_huw_container_disinfection: EcoNet/get_huw_container_disinfection
    sub_get_boiler_on_off: EcoNet/get_boiler_on_off
    sub_get_boiler_max_power_kw: EcoNet/get_boiler_max_power_kw
    sub_get_boiler_mid_power_kw: EcoNet/get_boiler_mid_power_kw
    sub_get_boiler_min_power_kw: EcoNet/get_boiler_min_power_kw
    sub_get_boiler_max_power_fan: EcoNet/get_boiler_max_power_fan
    sub_get_boiler_mid_power_fan: EcoNet/get_boiler_mid_power_fan
    sub_get_boiler_min_power_fan: EcoNet/get_boiler_min_power_fan
    sub_get_room_thermostat_summer_winter_mode: EcoNet/get_room_thermostat_summer_winter_mode
    sub_get_room_thermostat_night_temp: EcoNet/get_room_thermostat_night_temp
    sub_get_room_thermostat_day_temp: EcoNet/get_room_thermostat_day_temp
    sub_get_room_thermostat_operating_mode: EcoNet/get_room_thermostat_operating_mode
    sub_get_room_thermostat_hysteresis: EcoNet/get_room_thermostat_hysteresis


